# -*- coding: utf-8 -*-
"""cm_analyser_google_review.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AvWejxfVDnkM1mbL6GJvixIsB8uD0_4S
"""

import streamlit as st
import requests
from transformers import pipeline

st.set_page_config(page_title="Google Review Sentiment Analyzer", page_icon="🌍")

st.markdown("""
    <h2 style='text-align: center;'>🌍 Google Review Sentiment Analyzer</h2>

""", unsafe_allow_html=True)

# Load sentiment model
@st.cache_resource
def load_model():
    return pipeline("sentiment-analysis")

analyzer = load_model()

# User input
st.markdown("### 🏢 Enter Business Info")
business = st.text_input("Business Name (e.g., Starbucks)")
location = st.text_input("Location (e.g., Dhaka, Bangladesh)")

SERP_API_KEY = "15aae7e05c594f10ec289cdbbf03a6e116934c8c542e36634c08f6782cb6c56b"

def fetch_reviews(business, location):
    search_url = "https://serpapi.com/search.json"
    search_params = {
        "engine": "google_maps",
        "q": f"{business} {location}",
        "type": "search",
        "api_key": SERP_API_KEY
    }
    search_res = requests.get(search_url, params=search_params).json()
    try:
        data_id = search_res['local_results'][0]['data_id']
    except:
        return [], "❌ Business not found or SerpAPI error."

    review_params = {
        "engine": "google_maps_reviews",
        "data_id": data_id,
        "api_key": SERP_API_KEY
    }
    review_res = requests.get(search_url, params=review_params).json()
    return review_res.get("reviews", []), None

def analyze_reviews(reviews):
    results = []
    counts = {"POSITIVE": 0, "NEGATIVE": 0}

    for r in reviews:
        text = r.get("snippet", "")
        if not text.strip():
            continue
        sentiment = analyzer(text)[0]
        label = sentiment['label']
        score = sentiment['score']
        results.append({
            "text": text,
            "label": label,
            "score": score
        })
        if label in counts:
            counts[label] += 1

    return results, counts

if st.button("🔍 Analyze Reviews"):
    if business and location:
        with st.spinner("Fetching reviews..."):
            reviews, error = fetch_reviews(business, location)

        if error:
            st.error(error)
        elif not reviews:
            st.warning("⚠️ No reviews found.")
        else:
            with st.spinner("Analyzing sentiments..."):
                results, counts = analyze_reviews(reviews)

            st.success(f"✅ {len(results)} reviews analyzed.")
            st.markdown(f"""
                - 😊 Positive: {counts['POSITIVE']}
                - 😠 Negative: {counts['NEGATIVE']}
            """)

            st.markdown("### 📋 Sample Reviews")
            for r in results[:10]:
                label = "🟢 Positive" if r["label"] == "POSITIVE" else "🔴 Negative"
                st.markdown(f"> **{label}** ({r['score']:.2f}): {r['text']}")
    else:
        st.warning("Please enter both Business and Location.")